# Generated by Django 2.2 on 2019-04-15 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
        ('users', '0001_initial'),
        ('sales_logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleslog',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Agent'),
        ),
        migrations.AddField(
            model_name='saleslog',
            name='plan_sold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plans.Plan'),
        ),
    ]
