# Generated by Django 2.2 on 2019-04-15 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_logs', '0003_auto_20190415_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleslog',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Agent'),
        ),
    ]
