# Generated by Django 2.2 on 2019-04-15 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=32, verbose_name='name')),
                ('description', models.TextField(verbose_name='plan description')),
                ('cost', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
